services:
    backend.php:
        image: igorthefox/php-laravel-8-3-9:1.7
        ports:
            - '8080:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - my_expenses
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'my_expenses-mysql:/var/lib/mysql'
        #            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - my_expenses
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'my_expenses-redis:/data'
        networks:
            - my_expenses
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./.queue/data/:/var/lib/rabbitmq/
            - ./.queue/log/:/var/log/rabbitmq
        networks:
            - my_expenses
networks:
    my_expenses:
        driver: bridge
        external: true
volumes:
    my_expenses-mysql:
        driver: local
    my_expenses-redis:
        driver: local
